---
swagger: "2.0"
info:
  description: "This tool imports an encrypted Appatella export file into a Postgres database. See the [README.md](https://github.com/CMDT/AppatellaImportTool/blob/master/README.md) file for details."
  version: "0.0.1"
  title: "Appatella Import Tool"
  contact:
    name: "DigitalLabs@MMU"
    email: "l.cooper@mmu.ac.uk"
host: "localhost:8000"
basePath: "/apis"
schemes:
- "http"
paths:
  /import/:
    post:
      tags:
      - "import"
      summary: "Import a previously exported research snapshot into a local database."
      description: "Requires a snapshot zip and the encryption secret for decryption. WARNING the specified local database will be destroyed, before import."
      operationId: "postImport"
      consumes:
      - "application/json"
      parameters:
      - name: "source_path"
        in: "query"
        description: "The full path to your 7zip encrypted Appatella Export file."
        required: true
        type: "string"
      - name: "secret"
        in: "query"
        description: "The password used when the export was requested."
        required: true
        type: "string"
      - name: "destination_db"
        in: "query"
        description: "The name of the destination database. If it exists, the database will be dropped, and a new one created, to hold the new data."
        required: true
        type: "string"
      - name: "destination_username"
        in: "query"
        description: "The username you are using to connect to the database"
        required: true
        type: "string"
      - name: "destination_password"
        in: "query"
        description: "The password you are using to connect to the database. WARNING: Not masked. The password is visble."
        required: true
        type: "string"
      responses:
        "200":
          description: "Status 200"
        "400":
          description: ""
      x-swagger-router-controller: "Import"